# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: 归档
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_RELEASE_YAPI_IDEA_UPLOAD_PLUGIN}}
      run: |
        version=`cat build.gradle | grep -P "version '\\S+'" -o | sed "s/version '\(\S*\)'/\1/g"`
        hub release create -m "v$version" "v$version"
        hub release edit -a "build/libs/YapiIdeaUploadPlugin-$version.jar" -m "v$version" "v$version"
